name: Trivy Security Scan

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  trivy:
    uses: MARFI-Systems/trivy-security-scan/.github/workflows/trivy-scan.yml@7446cde8b4ca7180b65edd23f6e9fb16d1853916
